find_path(SQUIRREL_INCLUDE_DIR NAMES squirrel/sqstdio.h PATHS "${PROJECT_SOURCE_DIR}/dependencies/include")

find_path(SQUIRRELSQ_INCLUDE_DIR NAMES squirrel/squirrel.h   PATHS "${PROJECT_SOURCE_DIR}/dependencies/include")
find_library(SQUIRREL_LIBRARY NAMES sqstdio  PATHS "${PROJECT_SOURCE_DIR}/dependencies/lib")
find_library(SQUIRRELSQ_LIBRARY NAMES  squirrel PATHS "${PROJECT_SOURCE_DIR}/dependencies/lib")
 #   set(SQUIRREL_LIBRARIES ${SQUIRREL_LIBRARY})
#set(SQUIRREL_FOUND 1)

include(FindPackageHandleStandardArgs)
#find_package_handle_standard_args(Squirrel DEFAULT_MSG
#    SQUIRRELSQ_INCLUDE_DIR SQUIRREL_INCLUDE_DIR
#   SQUIRREL_LIBRARY SQUIRRELSQ_LIBRARY)

set(SQUIRREL_INCLUDE_DIRS ${SQUIRREL_INCLUDE_DIR} ${SQUIRRELSQ_INCLUDE_DIR})
set(SQUIRREL_LIBRARIES ${SQUIRREL_LIBRARY} ${SQUIRRELSQ_LIBRARY})
list(REMOVE_DUPLICATES SQUIRREL_INCLUDE_DIRS)
list(REMOVE_DUPLICATES SQUIRREL_LIBRARIES)
#mark_as_advanced(SQUIRRELSQ_INCLUDE_DIR SQUIRREL_INCLUDE_DIR)
#mark_as_advanced(SQUIRREL_LIBRARY SQUIRRELSQ_LIBRARY)



#find_path(OGGVORBIS_OGG_INCLUDE_DIR NAMES ogg/ogg.h PATHS "${PROJECT_SOURCE_DIR}/dependencies/include")
#find_path(OGGVORBIS_VORBIS_INCLUDE_DIR NAMES vorbis/vorbisfile.h PATHS "${PROJECT_SOURCE_DIR}/dependencies/include")
#find_library(OGGVORBIS_OGG_LIBRARY NAMES ogg Ogg libogg PATHS "${PROJECT_SOURCE_DIR}/dependencies/lib")
#find_library(OGGVORBIS_VORBIS_LIBRARY NAMES vorbis Vorbis libvorbis PATHS "${PROJECT_SOURCE_DIR}/dependencies/lib")
#find_library(OGGVORBIS_VORBISFILE_LIBRARY NAMES vorbisfile libvorbisfile PATHS "${PROJECT_SOURCE_DIR}/dependencies/lib")



# Publish variables
#set(OGGVORBIS_INCLUDE_DIRS ${OGGVORBIS_OGG_INCLUDE_DIR} ${OGGVORBIS_VORBIS_INCLUDE_DIR})
#set(OGGVORBIS_LIBRARIES ${OGGVORBIS_OGG_LIBRARY} ${OGGVORBIS_VORBIS_LIBRARY} ${OGGVORBIS_VORBISFILE_LIBRARY})
#list(REMOVE_DUPLICATES OGGVORBIS_INCLUDE_DIRS)
#list(REMOVE_DUPLICATES OGGVORBIS_LIBRARIES)
#mark_as_advanced(OGGVORBIS_OGG_INCLUDE_DIR OGGVORBIS_VORBIS_INCLUDE_DIR)
#mark_as_advanced(OGGVORBIS_OGG_LIBRARY OGGVORBIS_VORBIS_LIBRARY OGGVORBIS_VORBISFILE_LIBRARY)
